version: '2'

services:
    oracle_xe:
        image: christophesurmont/oracle-xe-11g
        environment:
            ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
            ORACLE_SID: xe
            TNS_ADMIN: $ORACLE_HOME/network/admin
            SQLPLUS: $ORACLE_HOME/bin/sqlplus
            ORACLE_DISABLE_ASYNCH_IO: 1
        ports:
            - '49160:22'
            - '49161:1521'

    php:
        image: fpfis/httpd-php-oci:7.3
        working_dir: /var/www/html
        ports:
        - 8080:8080
        volumes:
        - .:/var/www/html # Non Mac users.
        # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
        environment:
            XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        